version: '3.8'
services:
  app:
    build: .
    container_name: academic-management-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
      - ./prisma:/app/prisma
      - ./.env:/app/.env
    restart: unless-stopped 